In [56]:
pip install --upgrade git+https://github.com/JustAnotherArchivist/snscrape.git

Collecting git+https://github.com/JustAnotherArchivist/snscrape.git
  Cloning https://github.com/JustAnotherArchivist/snscrape.git to /private/var/folders/sm/45mbszrs44g00ht2h2b170gc0000gn/T/pip-req-build-sxpf8pu7
  Running command git clone -q https://github.com/JustAnotherArchivist/snscrape.git /private/var/folders/sm/45mbszrs44g00ht2h2b170gc0000gn/T/pip-req-build-sxpf8pu7
Requirement already satisfied: requests[socks] in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from snscrape==0.4.3.20220107.dev29+g77bbb9f) (2.27.1)
Requirement already satisfied: lxml in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from snscrape==0.4.3.20220107.dev29+g77bbb9f) (4.6.3)
Requirement already satisfied: beautifulsoup4 in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from snscrape==0.4.3.20220107.dev29+g77bbb9f) (4.9.3)
Requirement already satisfied: filelock in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from snscrape==0.4.3.20220107.dev29+g77bbb9f) (3.0.12)
Requirement already satisfied: pytz in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from snscrape==0.4.3.20220107.dev29+g77bbb9f) (2021.1)
Requirement already satisfied: soupsieve>1.2 in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from beautifulsoup4->snscrape==0.4.3.20220107.dev29+g77bbb9f) (2.2.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from requests[socks]->snscrape==0.4.3.20220107.dev29+g77bbb9f) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from requests[socks]->snscrape==0.4.3.20220107.dev29+g77bbb9f) (2020.12.5)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from requests[socks]->snscrape==0.4.3.20220107.dev29+g77bbb9f) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from requests[socks]->snscrape==0.4.3.20220107.dev29+g77bbb9f) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /Users/coeinneloh/opt/anaconda3/lib/python3.8/site-packages (from requests[socks]->snscrape==0.4.3.20220107.dev29+g77bbb9f) (1.7.1)
Building wheels for collected packages: snscrape
  Building wheel for snscrape (setup.py) ... done
  Created wheel for snscrape: filename=snscrape-0.4.3.20220107.dev29+g77bbb9f-py3-none-any.whl size=61523 sha256=47626eb42b19100b3b507b0903ece63d723c2e79771200b6668f367192b3d8ec
  Stored in directory: /private/var/folders/sm/45mbszrs44g00ht2h2b170gc0000gn/T/pip-ephem-wheel-cache-6_8901uo/wheels/92/42/87/33fa9b18f7a75d02643a9ca3743339aec9be28c6796267c7d8
Successfully built snscrape
Installing collected packages: snscrape
  Attempting uninstall: snscrape
    Found existing installation: snscrape 0.4.3.20220107.dev28+g57a624c
    Uninstalling snscrape-0.4.3.20220107.dev28+g57a624c:
      Successfully uninstalled snscrape-0.4.3.20220107.dev28+g57a624c
Successfully installed snscrape-0.4.3.20220107.dev29+g77bbb9f
Note: you may need to restart the kernel to use updated packages.

In [57]:
import pandas as pd
df= pd.read_csv("merged_data.csv")

In [58]:
df.head()

,Unnamed: 0,id,source,news_url,title,tweet_ids,target
0,0,2493749932,gossipcop,www.dailymail.co.uk/tvshowbiz/article-5874213/...,Did Miley Cyrus and Liam Hemsworth secretly ge...,284329075902926848\t284332744559968256\t284335...,0
1,1,4580247171,gossipcop,hollywoodlife.com/2018/05/05/paris-jackson-car...,Paris Jackson & Cara Delevingne Enjoy Night Ou...,992895508267130880\t992897935418503169\t992899...,0
2,2,941805037,gossipcop,variety.com/2017/biz/news/tax-march-donald-tru...,Celebrities Join Tax March in Protest of Donal...,853359353532829696\t853359576543920128\t853359...,0
3,3,2547891536,gossipcop,www.dailymail.co.uk/femail/article-3499192/Do-...,Cindy Crawford's daughter Kaia Gerber wears a ...,988821905196158981\t988824206556172288\t988825...,0
4,4,5476631226,gossipcop,variety.com/2018/film/news/list-2018-oscar-nom...,Full List of 2018 Oscar Nominations – Variety,955792793632432131\t955795063925301249\t955798...,0

In [59]:
df.dropna(subset = ['tweet_ids'], axis = 0, inplace=True)

In [60]:
import re
from re import split

df['tweet_ids'] = df['tweet_ids'].astype(str)

df['tweet_ids'] = df['tweet_ids'].apply(lambda x: str(x).replace('\t',' '))

In [61]:
df

,Unnamed: 0,id,source,news_url,title,tweet_ids,target
0,0,2493749932,gossipcop,www.dailymail.co.uk/tvshowbiz/article-5874213/...,Did Miley Cyrus and Liam Hemsworth secretly ge...,284329075902926848 284332744559968256 28433541...,0
1,1,4580247171,gossipcop,hollywoodlife.com/2018/05/05/paris-jackson-car...,Paris Jackson & Cara Delevingne Enjoy Night Ou...,992895508267130880 992897935418503169 99289952...,0
2,2,941805037,gossipcop,variety.com/2017/biz/news/tax-march-donald-tru...,Celebrities Join Tax March in Protest of Donal...,853359353532829696 853359576543920128 85335975...,0
3,3,2547891536,gossipcop,www.dailymail.co.uk/femail/article-3499192/Do-...,Cindy Crawford's daughter Kaia Gerber wears a ...,988821905196158981 988824206556172288 98882513...,0
4,4,5476631226,gossipcop,variety.com/2018/film/news/list-2018-oscar-nom...,Full List of 2018 Oscar Nominations – Variety,955792793632432131 955795063925301249 95579800...,0
...,...,...,...,...,...,...,...
23189,617,6931,politifact,http://www.politifact.com/truth-o-meter/promis...,The Obameter: Introduce a comprehensive immigr...,21096374968 21096771824 9413452992876544 12924...,1
23190,618,13619,politifact,http://www.cnn.com/2017/01/05/politics/border-...,"Trump asking Congress, not Mexico, to pay for ...",817357495047979008 817357627566985217 81735765...,1
23192,620,329,politifact,https://web.archive.org/web/20080131000131/htt...,Change We Can Believe In,634287923135909888 946743411100536832 94681610...,1
23194,622,4720,politifact,http://www.youtube.com/watch?v=EhyMplwY6HY,Romneys ProLife Conversion Myth or Reality Jun...,188871706637647874,1
23195,623,52,politifact,https://web.archive.org/web/20071102131244/htt...,Interest Group Ratings,1002208963239337984 1024651239697666048,1

In [62]:
df['tweet_ids'] = df['tweet_ids'].apply(lambda x: re.split(r' ', x))
df

,Unnamed: 0,id,source,news_url,title,tweet_ids,target
0,0,2493749932,gossipcop,www.dailymail.co.uk/tvshowbiz/article-5874213/...,Did Miley Cyrus and Liam Hemsworth secretly ge...,"[284329075902926848, 284332744559968256, 28433...",0
1,1,4580247171,gossipcop,hollywoodlife.com/2018/05/05/paris-jackson-car...,Paris Jackson & Cara Delevingne Enjoy Night Ou...,"[992895508267130880, 992897935418503169, 99289...",0
2,2,941805037,gossipcop,variety.com/2017/biz/news/tax-march-donald-tru...,Celebrities Join Tax March in Protest of Donal...,"[853359353532829696, 853359576543920128, 85335...",0
3,3,2547891536,gossipcop,www.dailymail.co.uk/femail/article-3499192/Do-...,Cindy Crawford's daughter Kaia Gerber wears a ...,"[988821905196158981, 988824206556172288, 98882...",0
4,4,5476631226,gossipcop,variety.com/2018/film/news/list-2018-oscar-nom...,Full List of 2018 Oscar Nominations – Variety,"[955792793632432131, 955795063925301249, 95579...",0
...,...,...,...,...,...,...,...
23189,617,6931,politifact,http://www.politifact.com/truth-o-meter/promis...,The Obameter: Introduce a comprehensive immigr...,"[21096374968, 21096771824, 9413452992876544, 1...",1
23190,618,13619,politifact,http://www.cnn.com/2017/01/05/politics/border-...,"Trump asking Congress, not Mexico, to pay for ...","[817357495047979008, 817357627566985217, 81735...",1
23192,620,329,politifact,https://web.archive.org/web/20080131000131/htt...,Change We Can Believe In,"[634287923135909888, 946743411100536832, 94681...",1
23194,622,4720,politifact,http://www.youtube.com/watch?v=EhyMplwY6HY,Romneys ProLife Conversion Myth or Reality Jun...,[188871706637647874],1
23195,623,52,politifact,https://web.archive.org/web/20071102131244/htt...,Interest Group Ratings,"[1002208963239337984, 1024651239697666048]",1

In [63]:
df['number_tweets']=df['tweet_ids'].apply(lambda x: len(x)).astype(int)
df

,Unnamed: 0,id,source,news_url,title,tweet_ids,target,number_tweets
0,0,2493749932,gossipcop,www.dailymail.co.uk/tvshowbiz/article-5874213/...,Did Miley Cyrus and Liam Hemsworth secretly ge...,"[284329075902926848, 284332744559968256, 28433...",0,97
1,1,4580247171,gossipcop,hollywoodlife.com/2018/05/05/paris-jackson-car...,Paris Jackson & Cara Delevingne Enjoy Night Ou...,"[992895508267130880, 992897935418503169, 99289...",0,15
2,2,941805037,gossipcop,variety.com/2017/biz/news/tax-march-donald-tru...,Celebrities Join Tax March in Protest of Donal...,"[853359353532829696, 853359576543920128, 85335...",0,86
3,3,2547891536,gossipcop,www.dailymail.co.uk/femail/article-3499192/Do-...,Cindy Crawford's daughter Kaia Gerber wears a ...,"[988821905196158981, 988824206556172288, 98882...",0,14
4,4,5476631226,gossipcop,variety.com/2018/film/news/list-2018-oscar-nom...,Full List of 2018 Oscar Nominations – Variety,"[955792793632432131, 955795063925301249, 95579...",0,66
...,...,...,...,...,...,...,...,...
23189,617,6931,politifact,http://www.politifact.com/truth-o-meter/promis...,The Obameter: Introduce a comprehensive immigr...,"[21096374968, 21096771824, 9413452992876544, 1...",1,137
23190,618,13619,politifact,http://www.cnn.com/2017/01/05/politics/border-...,"Trump asking Congress, not Mexico, to pay for ...","[817357495047979008, 817357627566985217, 81735...",1,976
23192,620,329,politifact,https://web.archive.org/web/20080131000131/htt...,Change We Can Believe In,"[634287923135909888, 946743411100536832, 94681...",1,182
23194,622,4720,politifact,http://www.youtube.com/watch?v=EhyMplwY6HY,Romneys ProLife Conversion Myth or Reality Jun...,[188871706637647874],1,1
23195,623,52,politifact,https://web.archive.org/web/20071102131244/htt...,Interest Group Ratings,"[1002208963239337984, 1024651239697666048]",1,2

In [64]:
df['id'].value_counts()

14920         2
14940         2
903731        1
882647        1
875857        1
             ..
922295        1
878569        1
15370         1
854708        1
5408886782    1
Name: id, Length: 21693, dtype: int64

In [65]:
df.reset_index(inplace = True)

In [1]:
from tqdm import tqdm
import snscrape.modules.twitter as sntwitter

tweet_data = []
for x in tqdm(range(len(df))):
    for t_id in df['tweet_ids'][x]:
        for i,tweet in enumerate(sntwitter.TwitterTweetScraper(tweetId=t_id,mode=sntwitter.TwitterTweetScraperMode.SINGLE).get_items()):
            tweet_data.append([df['id'][x],tweet.id, tweet.date, tweet.content,tweet.retweetCount,tweet.likeCount,tweet.replyCount,tweet.quoteCount])

tweet_df = pd.DataFrame(tweet_data, columns=['Id','Tweet_Id','Datetime','Text','Retweet','Like','Reply','Quote'])

NameError: name 'df' is not defined

In [69]:
tweet_df

,Id,Tweet_Id,Datetime,Text,Retweet,Like,Reply,Quote
0,7182,271683970989703168,2012-11-22 18:38:00+00:00,Viral post claims precinct in Allen West race ...,0,0,1,0
1,8470,1578922409,2009-04-21 21:51:08+00:00,"Your comments on CNN's ""State of the Union"" pr...",0,0,0,0
2,8470,8189638983,2010-01-25 12:22:07+00:00,Obama is going back on his word for no middle ...,0,0,0,0
3,8470,8305523803,2010-01-28 02:27:24+00:00,"CNN live-streaming & ""Connect w/ Facebook"" Pre...",0,0,0,0
4,8470,11218743375,2010-03-28 23:36:25+00:00,Post Politics: Find The Anger And Respect It: ...,0,0,0,0
...,...,...,...,...,...,...,...,...
127,15133,972625501532639232,2018-03-11 00:09:24+00:00,President Trump Massive MAGA Rally – Moon Town...,0,0,0,0
128,15133,972625742252199936,2018-03-11 00:10:22+00:00,@realDonaldTrump Dear Mr. President love to wa...,0,0,0,0
129,15133,972625787852677121,2018-03-11 00:10:32+00:00,#BreakingNews President Trump has taken the po...,0,0,1,0
130,15133,972625799986728960,2018-03-11 00:10:35+00:00,#MAGA Daddy Trump will make america great agai...,1,0,0,0
131,15133,972625926679805952,2018-03-11 00:11:06+00:00,#LIVE: President Donald Trump is in Moon Towns...,0,4,0,0

In [71]:
tweet_df.to_csv('21471_21474_tweet.csv', index=False)